### ISSUE TITLE
Mixed Rasch plots for P1

### ISSUE THREAD

**Issue by talbano** [pamelapsc/edps-845#1]
Hey Pam - the file I'm evaluating for P1 is at
pamelapsc/edps-845/Project/mixRaschTools/R/mixRasch.plot.R
Let me know if I'm not looking at the right file.

The first thing I noticed is that you seem to have a combination of old and new code in the mixRasch.plot function. I thought this, from lines 19 through 21:

``` R
  for (i in nc){
    plottemp <- sapply(x$LatentClass, function(x) x$item.par$delta.i)
  }
```

was supposed to be this:

``` R
    plottemp <- sapply(x$LatentClass, function(x) x$item.par$delta.i)
```

The `for (i in nc)` doesn't make sense to me. `nc` is a single value, not a vector that you're iterating through.
Can you post or email me a the threeclass-ex data file so I can test out your function? I see it in github, but it doesn't have a file extension. It should be threeclass-ex.rda or threeclass-ex.rdata. If you've got the data in R, you can save with `save(threeclass, file = "threeclass-ex.rda")` assuming the object is called `threeclass` in R.

**Comment by pamelapsc** [comment]
Tony, the correct file is named mixTaschTools. I intended to delete the file that ends in .plot but was having a lot of trouble with Github. 

Thanks,

Pam

**Comment by talbano** [comment]
OK. I just looked at mixRaschTools and my comments still apply. I think you're using a for loop when you don't need to. The sapply should suffice. Also, please point me to some example data so I can test the function. I could make up my own, but I want to make sure it's formatted correctly. Saving the data to your directory at edps-845/project would be best. Then, just add, commit, and push to github.

**Comment by pamelapsc** [comment]
Tony, there are two models saved in the project folder. If you go into P1, it can be loaded and tested. I couldn&#39;t figure out how to make that work in the project file. 

Pam

**Comment by pamelapsc** [comment]
Tony, we were on the road yesterday until late last night so it was difficult for me to follow this. Were you able to use the data I had in the project file to test the code?  If not, I am home now and can make any corrections needed.

Thanks,

Pam

**Comment by talbano** [comment]
No, can you just email them to me? Or are they too large?

Tony

Tony Albano
dadvswild.com <http://www.dadvswild.com>
mormon.org/me/2HY1 <http://www.mormon.org/me/2HY1>
cehs01.unl.edu/aalbano/

**Comment by talbano** [comment]
The data files fourclass-ex and threeclass-ex don't have any file extensions... They need to be .rda files as I indicated above.
