### ISSUE TITLE
P2 comments

### ISSUE THREAD

**Issue by jaydennord** [pamelapsc/edps-845#2]
# Documentation

I assume your P2 is under edps-845/Project/mixRaschTools/. I assume you adapted P1 into P2? If not, this commentary will be... maybe not helpful. 

You'll want to add `@export` to your roxygen comments in order to make the package functions usable when the user loads the package. 

I also noticed there was now "man" folder and no .Rd files for documentation. To get these, you can either use the command line or configure the build tools for a point-and-click method. Not sure whether you were in class for this part or not. 

In RStudio, assuming you have your project open, go to Build > Configure Build Tools...

![image](https://cloud.githubusercontent.com/assets/12644399/15768083/90a58c5a-2913-11e6-82b3-ac7c5fea8884.png)

Then check "Generate documentation with Roxygen". If you already have this, then oh well - at least I got to upload pictures which was neat.

![image](https://cloud.githubusercontent.com/assets/12644399/15768109/bc2d289c-2913-11e6-8dac-700dd2b08cba.png)

You should have a Build tab in your environment pane in RStudio. I think I (and others in class) had to reload RStudio to get the tab to show up. If you select the Build tab and click "More", there's a Document button. Press this to turn your roxygen comments into .Rd files.

![image](https://cloud.githubusercontent.com/assets/12644399/15768152/0cbe7fcc-2914-11e6-8263-91fcd90e0635.png)
# Functions

I'm looking at edps-845/Project/mixRaschTools/R/mixRaschTools.R. Again, not sure whether this is intended for P2.

Your functions have an argument `x` which is not documented. With `@param`, you refer to an argument called `modelname` which I assume is meant to be the `x` argument?

Also, your functions are dependent on `x` having list elements `LatentClass`, `item.par$delta.i`, `person.par$theta`. If `x` is supposed to be a "fitted multiple class mixture Rasch model", I wonder if such an outputted model has some class which you can check for before running the rest of the function. That is, within your functions, check that `x` is of the correct class; if not, use `stop()` to give the user some meaningful message for why the function is borked.

If you find that the Rasch model has some specific class, you can check that `x` has that class by following the example code:

``` r
# Just setting up some object with custom classes...
x <- 1:10
class(x) <- c("MEOW", "WOOF")

# check that x has class "MEOW"
"MEOW" %in% attributes(x)$class
```

If the "fitted multiple class mixture Rasch model" doesn't have any specific class attribute, you could just check that `x` has list elements `LatentClass`, `item.par$delta.i`, `person.par$theta` and terminate the function if it doesn't.

**Comment by pamelapsc** [comment]
Thank you very much for your help. Your assumption was correct, and clearly I missed more than I thought when I had to leave early!  Much appreciated.
